/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * KuvelaMDI.java
 *
 * Created on 12-Sep-2011, 4:17:46 PM
 */
package org.medicmobile.projects.desktop.kuvela.ui;

import java.awt.EventQueue;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import org.medicmobile.projects.desktop.kuvela.reader.MessageReader;

/**
 *
 * @author Kimando Emmanuel
 * @mail kimando@medicmobile.org
 * 
 */
public class KuvelaMDI extends javax.swing.JFrame
{

    /** Creates new form KuvelaMDI */
    public KuvelaMDI()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        vcmrMenuItem = new javax.swing.JMenuItem();
        fsMenuItem = new javax.swing.JMenuItem();
        incentivesAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kuvela");

        fileMenu.setMnemonic('f');
        fileMenu.setText("Reports");

        vcmrMenuItem.setMnemonic('o');
        vcmrMenuItem.setText("Village Clinic Monthly Report");
        vcmrMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vcmrMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(vcmrMenuItem);

        fsMenuItem.setMnemonic('s');
        fsMenuItem.setText("Facility Stock");
        fsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fsMenuItem);

        incentivesAsMenuItem.setMnemonic('a');
        incentivesAsMenuItem.setText("Incentives");
        incentivesAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incentivesAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(incentivesAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1297, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

private void vcmrMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vcmrMenuItemActionPerformed
  
    EventQueue.invokeLater(new Runnable()
    {
        public void run()
        {
            JInternalFrame internal = new JInternalFrame("Village Clinic Monthly Report");
            internal.add(new VillageClinicMonthyReport());
            internal.pack();
            internal.setVisible(true);

            desktopPane.removeAll();
            desktopPane.repaint();

            desktopPane.add(internal);
        }
    });
}//GEN-LAST:event_vcmrMenuItemActionPerformed

private void fsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsMenuItemActionPerformed
    
    EventQueue.invokeLater(new Runnable()
    {
        public void run()
        {
            JInternalFrame internal = new JInternalFrame("Facility Stock");
            internal.add(new FacilityStock());
            internal.pack();
            internal.setVisible(true);

            desktopPane.removeAll();
            desktopPane.repaint();

            desktopPane.add(internal);
        }
    });
}//GEN-LAST:event_fsMenuItemActionPerformed

private void incentivesAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incentivesAsMenuItemActionPerformed
    
    EventQueue.invokeLater(new Runnable()
    {
        public void run()
        {
            JInternalFrame internal = new JInternalFrame("Incentives");
            internal.add(new PointsManager());
            internal.pack();
            internal.setVisible(true);

            desktopPane.removeAll();
            desktopPane.repaint();

            desktopPane.add(internal);
        }
    });
}//GEN-LAST:event_incentivesAsMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(KuvelaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(KuvelaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(KuvelaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(KuvelaMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                try
                {
                    MessageReader reader = new MessageReader("COM3");
                    reader.readMessages();

                } catch (Exception e)
                {
                    System.out.println(e.getMessage());
                }
                new KuvelaMDI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem fsMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem incentivesAsMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem vcmrMenuItem;
    // End of variables declaration//GEN-END:variables
}
